.github/publish_docs.yaml

Add workflow to publish docs

---

en/mkdocs.yml

Fix base path

---

en/docs/samples/PublishKafkaInCustomAvroFormat.md

Update the `PublishKafkaInCustomAvroFormat` sample

---

en/docs/samples/PublishHttpOAuthRequestWithoutAccessToken.md
en/mkdocs.yml

Update page `Publishing HTTP Events to an OAuth-protected Endpoint without an Access Token`

Update page `OAuth-protected Endpoint without an Access Token`

---

en/docs/samples/PublishHttpOAuthRequestWithOAuthUser.md

Update `Publishing HTTP Events to an OAuth-protected Endpoint`

---

en/docs/quick-start-guide/quick-start-guide.md

Update quick start guide

---

en/docs/samples/PublishHTTPInJsonFormatWithCustomMapping.md
en/docs/samples/PublishHttpInJsonFormat.md
en/docs/samples/PublishHttpInXmlFormat.md
en/docs/samples/PublishHttpInXmlFormatWithCustomMapping.md
en/docs/samples/ReceiveAndCount.md
en/docs/samples/ReceiveHTTPInJsonFormatWithCustomMapping.md
en/docs/samples/ReceiveHTTPInJsonFormatWithDefaultMapping.md
en/docs/samples/ReceiveHTTPInXMLFormatWithDefaultMapping.md
en/docs/samples/ReceiveHTTPinXMLFormatWithCustomMapping.md

Update HTTP samples

---

en/docs/samples/CDCWithListeningMode.md
en/docs/samples/CDCWithPollingMode.md

Update CDC samples

---

en/docs/samples/PublishTcpInBinaryFormat.md
en/docs/samples/PublishTcpInJsonFormat.md
en/docs/samples/PublishTcpInTextFormat.md

Update TCP publish samples

---

en/docs/samples/PublishHttpOAuthRequest.md

Update the `Publishing HTTP Events to to an OAuth-protected Endpoint`

---

en/docs/samples/PublishHttpOAuthRequestWithRefreshToken.md

Update Publishing `HTTP Events to an OAuth-protected Endpoint while Using a Refresh Token Grant Type`

---

en/docs/samples/PublishHttpOAuthRequestResponse.md

Update `Publishing HTTP Events via an OAuth-protected Endpoint`

---

en/docs/samples/PublishMqttInXmlFormat.md
en/docs/samples/ReceiveMQTTInXMLFormat.md

Update Publish and Receive MQTT Event Pages

---

en/docs/samples/PublishHl7InXmlFormat.md
en/docs/samples/ReceiveHl7InXmlFormat.md

Update HL7 publish and receive in XML pages

---

en/docs/samples/PublishKafkaInAvroFormatUsingSchemaRegistry.md

Update `Publishing Avro Events via Kafka` page

---

en/docs/samples/store-mongodb.md

Update the `MongoDB` page

---

en/docs/samples/PublishHl7InER7Format.md
en/docs/samples/ReceiveHl7InER7Format.md

Update Publish and Receive of HL7 in ER7 format examples

---

en/docs/samples/AmazonS3SinkSample.md

Update Amazon S3 sink page

---

en/docs/examples/performing-real-time-etl-with-files.md
en/docs/examples/working-with-kafka.md

Update kafka and file etl tutorial pages

---

en/docs/samples/CSVCustomMapping.md
en/docs/samples/CSVDefaultMapping.md
en/docs/samples/ReceiveEventsFromFile.md

Update csv mapping samples

---

en/docs/samples/PublishRabbitmqInXmlFormat.md
en/docs/samples/ReceiveRabbitmqInJSONFormat.md

Update rabbitmq samples

---

en/docs/samples/PublishWebSocketInXmlFormat.md
en/docs/samples/ReceiveWebSocketInXMLFormat.md

Update websocket samples

---

en/docs/samples/PublishJmsInKeyvalueFormat.md
en/docs/samples/PublishJmsInXmlFormat.md
en/docs/samples/ReceiveJMSInJsonFormat.md
en/docs/samples/ReceiveJMSInKeyvalueFormat.md

Update jms samples

---

en/docs/setup/deploying-si-as-a-single-deployment.md
en/docs/setup/deploying-si-as-an-active-active-deployment.md
en/docs/setup/deploying-si-as-minimum-ha-cluster-in-aws-ecs.md
en/docs/setup/deploying-si-as-minimum-ha-cluster.md

Adjustment to deploy pages

---

en/docs/assets/css/blue-palette-alt1.css
en/docs/index.md
en/docs/overview/overview.md

Update index and overview pages

---

en/docs/samples/HelloKafka.md
en/docs/samples/PublishKafkaInBinaryFormat.md
en/docs/samples/PublishKafkaInJsonFormat.md
en/docs/samples/ReceiveKafkaInBinaryFormat.md
en/docs/samples/ReceiveKafkaInTextFormatWithCustomMapping.md

Update kafka samples

---

en/docs/samples/MapExtensionSample.md
en/docs/samples/RegexExecutionSample.md
en/docs/samples/Store-rdbms.md
en/docs/samples/StringExtensionSample.md
en/docs/samples/SweetProductionDataPreprocessing.md

Update the extension and rdbms sample

---

en/docs/samples/Store-cassandra.md
en/docs/samples/store-mongodb.md

Update mongo and cassandra stores pages

---

CNAME

> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …

Add Cname file

---

en/docs/get-started/about-this-release.md
en/mkdocs.yml

Add about release page

---

en/docs/develop/si-for-vscode-overview.md

Fix SI vscode starting page description

---

.github/workflows/publish_docs.yaml

$ subject 
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type …

[4.3.0] Rename 4.3.0 branch tag to `4.3.0 and older`
